PATH_DATA_RESOURCE = "/Users/seong-taekhong/dev/f1-data-playground/resources/f1_data_set"

FILE_CIRCUITS = joinpath(PATH_DATA_RESOURCE, "circuits.csv")
FILE_CONSTRUCTORS = joinpath(PATH_DATA_RESOURCE, "constructors.csv")
FILE_CONSTRUCTOR_RESULTS = joinpath(PATH_DATA_RESOURCE, "constructor_results.csv")
FILE_CONSTRUCTOR_STANDINGS = joinpath(PATH_DATA_RESOURCE, "constructor_standings.csv")
FILE_DRIVER_STANDINGS = joinpath(PATH_DATA_RESOURCE, "driver_standings.csv")
FILE_DRIVERS = joinpath(PATH_DATA_RESOURCE, "drivers.csv")
FILE_LAP_TIMES = joinpath(PATH_DATA_RESOURCE, "lap_times.csv")
FILE_PIT_STOPS = joinpath(PATH_DATA_RESOURCE, "pit_stops.csv")
FILE_QUALIFYING = joinpath(PATH_DATA_RESOURCE, "qualifying.csv")
FILE_RACES = joinpath(PATH_DATA_RESOURCE, "races.csv")
FILE_RESULTS = joinpath(PATH_DATA_RESOURCE, "results.csv")
FILE_SEASONS = joinpath(PATH_DATA_RESOURCE, "seasons.csv")
FILE_STATUS = joinpath(PATH_DATA_RESOURCE, "status.csv")
